set(_CATKIN_CURRENT_PACKAGE "speech")
set(speech_VERSION "0.0.0")
set(speech_MAINTAINER "znfs <znfs@todo.todo>")
set(speech_PACKAGE_FORMAT "2")
set(speech_BUILD_DEPENDS "roscpp" "rospy" "std_msgs" "message_generation")
set(speech_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(speech_BUILDTOOL_DEPENDS "catkin")
set(speech_BUILDTOOL_EXPORT_DEPENDS )
set(speech_EXEC_DEPENDS "roscpp" "rospy" "std_msgs" "message_runtime")
set(speech_RUN_DEPENDS "roscpp" "rospy" "std_msgs" "message_runtime")
set(speech_TEST_DEPENDS )
set(speech_DOC_DEPENDS )
set(speech_URL_WEBSITE "")
set(speech_URL_BUGTRACKER "")
set(speech_URL_REPOSITORY "")
set(speech_DEPRECATED "")